language: php

php:
  - 5.3
  - 5.4
  - 5.5

services:
  - mongodb

notifications:
  email:
    - daniel.gonzalez@freelancemadrid.es

before_script:
#  - pecl -q install mongo && echo "extension=mongo.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - composer install
